//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacenProductos
    {
        public int id { get; set; }
        public int idAlmacen { get; set; }
        public int idProducto { get; set; }
        public int cantidadProducto { get; set; }
    
        public virtual almacen almacen { get; set; }
        public virtual almacen almacen1 { get; set; }
        public virtual productos productos { get; set; }
        public virtual productos productos1 { get; set; }
    }
}
