//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendarios
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idTipo { get; set; }
        public int idDescuento { get; set; }
        public int estatus { get; set; }
    
        public virtual descuentos descuentos { get; set; }
        public virtual descuentos descuentos1 { get; set; }
        public virtual tiposDescuentos tiposDescuentos { get; set; }
        public virtual tiposDescuentos tiposDescuentos1 { get; set; }
    }
}
