//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apePaterno { get; set; }
        public string apeMaterno { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string razonSocial { get; set; }
        public int idTipoCliente { get; set; }
        public int estatus { get; set; }
    
        public virtual tiposClientes tiposClientes { get; set; }
        public virtual tiposClientes tiposClientes1 { get; set; }
    }
}
