//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas
    {
        public int id { get; set; }
        public string folio { get; set; }
        public System.DateTime fechaCreaion { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public decimal monto { get; set; }
    }
}
