//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentaCamionesEntities : DbContext
    {
        public RentaCamionesEntities()
            : base("name=RentaCamionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<almacen> almacen { get; set; }
        public virtual DbSet<almacenProductos> almacenProductos { get; set; }
        public virtual DbSet<calendarios> calendarios { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<descuentos> descuentos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<estatusRenta> estatusRenta { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<marcasProd> marcasProd { get; set; }
        public virtual DbSet<modulos> modulos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<puesto> puesto { get; set; }
        public virtual DbSet<rentaDetalle> rentaDetalle { get; set; }
        public virtual DbSet<rentas> rentas { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<rolesUsuarioModulo> rolesUsuarioModulo { get; set; }
        public virtual DbSet<tiposClientes> tiposClientes { get; set; }
        public virtual DbSet<tiposDescuentos> tiposDescuentos { get; set; }
        public virtual DbSet<tiposProductos> tiposProductos { get; set; }
        public virtual DbSet<unidadesMedida> unidadesMedida { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
