//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.almacenProductos = new HashSet<almacenProductos>();
            this.almacenProductos1 = new HashSet<almacenProductos>();
            this.rentaDetalle = new HashSet<rentaDetalle>();
            this.rentaDetalle1 = new HashSet<rentaDetalle>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int numeroSerie { get; set; }
        public string estadoFisico { get; set; }
        public int numeroExistencias { get; set; }
        public int estatus { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public int idUM { get; set; }
        public int idMarca { get; set; }
        public int idTipoProd { get; set; }

        // Datos de detalle para mostrar
        public int cantidad { get; set; }
        public string marca { get; set; }
        public string unidadMedida { get; set; }
        public string categoria { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<almacenProductos> almacenProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<almacenProductos> almacenProductos1 { get; set; }
        public virtual marcasProd marcasProd { get; set; }
        public virtual marcasProd marcasProd1 { get; set; }
        public virtual tiposProductos tiposProductos { get; set; }
        public virtual tiposProductos tiposProductos1 { get; set; }
        public virtual unidadesMedida unidadesMedida { get; set; }
        public virtual unidadesMedida unidadesMedida1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentaDetalle> rentaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentaDetalle> rentaDetalle1 { get; set; }
    }
}
