//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class rentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rentas()
        {
            this.rentaDetalle = new HashSet<rentaDetalle>();
            this.rentaDetalle1 = new HashSet<rentaDetalle>();
        }
    
        public int id { get; set; }
        public string folio { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fechaCreacion { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fechaModificacion { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fechaRenta { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fechaVence { get; set; }
        public decimal subtotal { get; set; }
        public decimal total { get; set; }
        public int cantidadTotalProd { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentaDetalle> rentaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rentaDetalle> rentaDetalle1 { get; set; }
    }
}
