//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentaDetalle
    {
        public int id { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public int entregado { get; set; }
        public int idRenta { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual productos productos1 { get; set; }
        public virtual rentas rentas { get; set; }
        public virtual rentas rentas1 { get; set; }
    }
}
