//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterDetailV2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolesUsuarioModulo
    {
        public int id { get; set; }
        public int idRol { get; set; }
        public int idUsuario { get; set; }
        public int idModulo { get; set; }
    
        public virtual modulos modulos { get; set; }
        public virtual modulos modulos1 { get; set; }
        public virtual roles roles { get; set; }
        public virtual roles roles1 { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual usuarios usuarios1 { get; set; }
    }
}
